Create tests.py
django.db.utils.ProgrammingError: relation "meeting" does not exist
LINE 1: ..."meetinglocation", "meeting"."meetingagenda" FROM "meeting" ...